// Generated by build-tokens.mjs – do not edit by hand
import rawTokens from './tokens.json';

type DeepReadonly<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends object
    ? { readonly [K in keyof T]: DeepReadonly<T[K]> }
    : T;

export const tokens: DeepReadonly<typeof rawTokens> = rawTokens;
export type AdsTokens = typeof tokens;
